[package]
name = "rest_api_empleados"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.7", features = [ "runtime-tokio", "mysql", "chrono" ] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["full"] }